version: '2'
services:
    acme_site-mysql:
        container_name: acme_site-mysql
        image: mysql:5.7.11
        # volumes:
        #     - ~/volumes/jhipster/acme_site/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=acme_site
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
